core/src/main/java/com/usthe/sureness/provider/ducument/DocumentResourceDefaultProvider.java
fix too much read sureness.yml times when auth may make system down
=> fix too much read sureness.yml times when auth may make system down

samples/javalin-sureness/pom.xml, samples/javalin-sureness/src/main/java/com/usthe/sureness/javalin/Application.java, samples/javalin-sureness/src/main/resources/sureness.yml, samples/ktor-sureness/pom.xml, samples/pom.xml
support example use sureness protect javalin- https://javalin.io/
=> support sample javalin-sureness

samples/pom.xml, samples/spring-webflux-support/pom.xml, samples/spring-webflux-support/src/main/java/com/usthe/sureness/spring/webflux/SpringBootApplication.java, samples/spring-webflux-support/src/main/java/com/usthe/sureness/spring/webflux/SurenessConfiguration.java, samples/spring-webflux-support/src/main/java/com/usthe/sureness/spring/webflux/SurenessFilterExample.java, samples/spring-webflux-support/src/main/java/com/usthe/sureness/spring/webflux/controller/ExampleController.java, samples/spring-webflux-support/src/main/java/com/usthe/sureness/spring/webflux/controller/SimulateController.java, samples/spring-webflux-support/src/main/java/com/usthe/sureness/spring/webflux/support/BasicSubjectReactiveCreator.java, samples/spring-webflux-support/src/main/java/com/usthe/sureness/spring/webflux/support/JwtSubjectReactiveCreator.java, samples/spring-webflux-support/src/main/java/com/usthe/sureness/spring/webflux/support/NoneSubjectReactiveCreator.java, samples/spring-webflux-support/src/main/resources/application.yml, samples/spring-webflux-support/src/main/resources/sureness.yml
=> add support spring-webflux

core/pom.xml, core/src/main/java/com/usthe/sureness/util/JsonWebTokenUtil.java, core/src/test/java/com/usthe/sureness/subject/creater/JwtSubjectServletCreatorTest.java, core/src/test/java/com/usthe/sureness/util/JsonWebTokenUtilTest.java, sample-bootstrap/src/main/java/com/usthe/sureness/sample/bootstrap/controller/AccountController.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/controller/AccountController.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/config/SurenessConfiguration.java
update jwt util set hmac algorithm as default
=> update jwt util set hmac algorithm as default

core/src/main/java/com/usthe/sureness/DefaultSurenessConfig.java, core/src/main/java/com/usthe/sureness/processor/exception/NeedDigestInfoException.java, core/src/main/java/com/usthe/sureness/processor/support/DigestProcessor.java, core/src/main/java/com/usthe/sureness/subject/creater/DigestSubjectJaxRsCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/DigestSubjectServletCreator.java, core/src/main/java/com/usthe/sureness/subject/support/DigestSubject.java, core/src/main/resources/sureness-sample.yml, sample-bootstrap/src/main/java/com/usthe/sureness/sample/bootstrap/SurenessFilterExample.java, sample-bootstrap/src/main/resources/sureness.yml, samples/javalin-sureness/src/main/resources/sureness.yml, samples/ktor-sureness/resources/sureness.yml, samples/quarkus-sureness/src/main/resources/sureness.yml
we already have completed the basic auth, bearer jwt token auth support.
we should support the digest auth by default in sureness.
=> Digest auth feature - support digest auth with servlet and jax-rs

core/src/main/java/com/usthe/sureness/processor/support/JwtProcessor.java, core/src/main/java/com/usthe/sureness/util/JsonWebTokenUtil.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/config/SurenessConfiguration.java
fix #30 throw uncatched exception when request jwt is not base64
=> fix #30 throw uncatched exception when request jwt is not base64

sample-tom/README_CN.md, sample-tom/sample-tom-postman.json, sample-tom/src/main/java/com/usthe/sureness/sample/tom/controller/AccountController.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/controller/TokenStorage.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/SurenessFilterExample.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/config/SurenessConfiguration.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/processor/CustomTokenProcessor.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/processor/RefreshExpiredTokenException.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/subject/CustomPasswdSubjectCreator.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/subject/CustomTokenSubject.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/subject/CustomTokenSubjectCreator.java, sample-tom/src/main/resources/db/data.sql
Feature support a all custom process flow example in sampel-tom
1. custom subject subjectCreator processor
2. support refresh token demo
=> Feature support a all custom process flow example

core/src/main/java/com/usthe/sureness/subject/creater/JwtSubjectJaxRsCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/JwtSubjectServletCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/NoneSubjectJaxRsCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/NoneSubjectServletCreator.java, core/src/main/java/com/usthe/sureness/util/SurenessCommonUtil.java, core/src/test/java/com/usthe/sureness/util/SurenessCommonUtilTest.java
Deprecated SurenessCommonUtil.findUserAgent
=> bugfix - Deprecated SurenessCommonUtil.findUserAgent

core/src/main/java/com/usthe/sureness/provider/annotation/AnnotationLoader.java
=> bugfix-@RequiresRoles can not support one more role#38

core/src/main/java/com/usthe/sureness/DefaultSurenessConfig.java, core/src/main/java/com/usthe/sureness/matcher/PathTreeProvider.java, core/src/main/java/com/usthe/sureness/mgt/SurenessSecurityManager.java, core/src/main/java/com/usthe/sureness/provider/annotation/AnnotationLoader.java, core/src/main/java/com/usthe/sureness/provider/ducument/DocumentResourceDefaultProvider.java, core/src/main/java/com/usthe/sureness/util/SurenessCommonUtil.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/provider/ResourceProvider.java
support  web server context path setting   
context path:    
eg: springboot context path is: server.servlet.context-path = v2    
tomcat context path is: <context path="v2">    
See:    
````
PathTreeProvider -> setContextPath(String contextPath)
````
and remove some deprecated method
=> Feature context path

core/src/main/java/com/usthe/sureness/matcher/DefaultPathRoleMatcher.java
Support simultaneous loading of multiple path data sources
eg: simultaneous loading databaseProvider and AnnotationLoader to provider path tree data
=> Feature support simultaneous loading of multiple path data sources

core/src/main/java/com/usthe/sureness/processor/BaseProcessor.java
fix can not get principal in jwt proc, detail see #50
=> fix #50, can not get principal in jwt proc

core/pom.xml, core/src/main/java/com/usthe/sureness/util/ClassScanner.java, core/src/test/java/com/usthe/sureness/DefaultSurenessConfigTest.java, core/src/test/java/com/usthe/sureness/matcher/DefaultPathRoleMatcherTest.java, core/src/test/java/com/usthe/sureness/matcher/util/TirePathTreeTest.java, core/src/test/java/com/usthe/sureness/subject/SurenessSubjectFactoryTest.java, core/src/test/java/com/usthe/sureness/subject/creater/BasicSubjectServletCreatorTest.java, core/src/test/java/com/usthe/sureness/subject/creater/DigestSubjectServletCreatorTest.java, core/src/test/java/com/usthe/sureness/subject/creater/JwtSubjectServletCreatorTest.java, core/src/test/java/com/usthe/sureness/subject/creater/NoneSubjectServletCreatorTest.java, core/src/test/java/com/usthe/sureness/util/ClassScannerTest.java, core/src/test/java/com/usthe/sureness/util/JsonWebTokenUtilTest.java, core/src/test/java/com/usthe/sureness/util/Md5UtilTest.java, core/src/test/java/com/usthe/sureness/util/SurenessCommonUtilTest.java, core/src/test/java/com/usthe/sureness/util/SurenessContextHolderTest.java
update junit5 and add more test case
=> update junit5 and add more test case

core/src/main/java/com/usthe/sureness/DefaultSurenessConfig.java, core/src/main/java/com/usthe/sureness/provider/annotation/AnnotationPathTreeProvider.java, core/src/main/java/com/usthe/sureness/provider/ducument/DocumentAccountProvider.java, core/src/main/java/com/usthe/sureness/provider/ducument/DocumentPathTreeProvider.java, core/src/main/java/com/usthe/sureness/provider/ducument/DocumentResourceAccess.java, core/src/main/java/com/usthe/sureness/provider/ducument/DocumentResourceDefaultProvider.java, core/src/test/java/com/usthe/sureness/provider/annotation/AnnotationPathTreeProviderTest.java, core/src/test/java/com/usthe/sureness/provider/ducument/DocumentPathTreeProviderTest.java, core/src/test/java/com/usthe/sureness/provider/ducument/DocumentResourceAccessTest.java, docs/annotation-datasource.md, docs/cn/annotation-datasource.md, sample-bootstrap/src/main/java/com/usthe/sureness/sample/bootstrap/controller/AccountController.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/controller/AnnotationController.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/config/SurenessConfiguration.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/provider/DatabaseAccountProvider.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/provider/DatabasePathTreeProvider.java, sample-tom/src/main/resources/sureness.yml, samples/spring-webflux-sureness/src/main/java/com/usthe/sureness/spring/webflux/SurenessConfiguration.java
split provider, support multi path tree resource provider    
add more test case    
update doc
=> split provider, support multi path tree resource provider

core/src/main/java/com/usthe/sureness/subject/creater/BasicSubjectJaxRsCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/BasicSubjectServletCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/DigestSubjectJaxRsCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/DigestSubjectServletCreator.java, core/src/test/java/com/usthe/sureness/subject/SurenessSubjectFactoryTest.java
bugfix basic creator error when base64 error    
bugfix digest creator error create when request is basic or jwt auth
=> fix basic creator error when base64 error, fix digest creator error create when request is basic or jwt auth

core/src/main/java/com/usthe/sureness/subject/PrincipalMap.java, core/src/main/java/com/usthe/sureness/subject/Subject.java, core/src/main/java/com/usthe/sureness/subject/SubjectSum.java, core/src/main/java/com/usthe/sureness/subject/support/DigestSubject.java, core/src/main/java/com/usthe/sureness/subject/support/JwtSubject.java, core/src/main/java/com/usthe/sureness/subject/support/NoneSubject.java, core/src/main/java/com/usthe/sureness/subject/support/PasswordSubject.java, core/src/main/java/com/usthe/sureness/subject/support/SinglePrincipalMap.java, core/src/main/java/com/usthe/sureness/subject/support/SurenessSubjectSum.java, sample-bootstrap/pom.xml, sample-bootstrap/src/main/java/com/usthe/sureness/sample/bootstrap/SurenessFilterExample.java, sample-bootstrap/src/main/java/com/usthe/sureness/sample/bootstrap/config/SwaggerConfiguration.java, sample-bootstrap/src/main/resources/sureness.yml, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/subject/CustomTokenSubject.java
add swagger in sample-bootstrap   
add multi PrincipalMap in subject and SubjectSum
=> Feature multi principal

core/src/main/java/com/usthe/sureness/util/JsonWebTokenUtil.java
=> jwt 增加请求头认证参数信息，方便用户扩展参数

core/src/main/java/com/usthe/sureness/util/JsonWebTokenUtil.java, core/src/test/java/com/usthe/sureness/util/JsonWebTokenUtilTest.java
add test for https://github.com/tomsun28/sureness/pull/62
=> add more test for jwt util

core/src/main/java/com/usthe/sureness/matcher/DefaultPathRoleMatcher.java, core/src/main/java/com/usthe/sureness/matcher/util/TirePathTree.java, core/src/test/java/com/usthe/sureness/matcher/util/TirePathTreeTest.java
bugfix: process authorized can not match roles when role name is upper.
=> process authorized can not match roles when role name is upper

core/src/main/java/com/usthe/sureness/processor/support/JwtProcessor.java, core/src/main/java/com/usthe/sureness/subject/support/DigestSubject.java, core/src/main/java/com/usthe/sureness/subject/support/JwtSubject.java, core/src/main/java/com/usthe/sureness/subject/support/PasswordSubject.java
support digest,basic subject principalMap   
support jwt subject principalMap
=> Feature support subject principal map

README.md, README_CN.md, docs/README.md, docs/_sidebar.md, docs/custom-datasource.md, docs/custom-processor.md, docs/custom-subject-creator.md, docs/custom-subject.md, docs/quickstart.md
=> Feature update english docs

core/src/main/java/com/usthe/sureness/processor/BaseProcessor.java, core/src/main/java/com/usthe/sureness/processor/support/DigestProcessor.java, core/src/main/java/com/usthe/sureness/processor/support/JwtProcessor.java, core/src/main/java/com/usthe/sureness/processor/support/PasswordProcessor.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/processor/CustomTokenProcessor.java
implement authorized default in BaseProcessor, other processors can use default.
=> implement authorized default in BaseProcessor

core/src/main/java/com/usthe/sureness/DefaultSurenessConfig.java, core/src/main/java/com/usthe/sureness/processor/BaseProcessor.java, core/src/main/java/com/usthe/sureness/subject/creater/JwtSubjectWsJaxRsCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/JwtSubjectWsServletCreator.java, core/src/main/java/com/usthe/sureness/util/JsonWebTokenUtil.java, sample-bootstrap/pom.xml, sample-bootstrap/src/main/java/com/usthe/sureness/sample/bootstrap/config/WebSocketConfig.java, sample-bootstrap/src/main/java/com/usthe/sureness/sample/bootstrap/controller/WebSocketEndpoint.java, sample-bootstrap/src/main/resources/sureness.yml, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/processor/CustomTokenProcessor.java
support websocket auth jwt feature    
use:  new WebSocket("ws://localhost:8088/webSocket/demo?token=jwtValue-eyJhbGciOiJIUz");
=> support websocket jwt auth feature    

core/src/main/java/com/usthe/sureness/subject/support/SinglePrincipalMap.java, core/src/main/java/com/usthe/sureness/subject/support/SurenessSubjectSum.java, sample-bootstrap/src/main/java/com/usthe/sureness/sample/bootstrap/SurenessFilterExample.java, sample-bootstrap/src/main/java/com/usthe/sureness/sample/bootstrap/controller/WebSocketEndpoint.java
feature: storage subject info in websocket session
=> feature: storage subject info in websocket session

core/src/main/java/com/usthe/sureness/security/XssSqlServletRequestWrapper.java, core/src/main/java/com/usthe/sureness/security/XssSqlUtil.java, sample-bootstrap/src/main/java/com/usthe/sureness/sample/bootstrap/SurenessFilterExample.java
add xss, sql inject filter util   
sample-bootstrap use xss sql filter
=> support filter xss, sql inject 

.github/workflows/issues-translator.yml
update translator action v2.4 to v2.5
=> update translator action v2.5

core/src/main/java/com/usthe/sureness/matcher/util/TirePathTree.java, core/src/main/resources/sureness-sample.yml, core/src/test/java/com/usthe/sureness/matcher/util/TirePathTreeTest.java, core/src/test/java/com/usthe/sureness/provider/ducument/DocumentPathTreeProviderTest.java, docs/cn/default-datasource.md, docs/cn/path-match.md, docs/default-datasource.md, docs/path-match.md, sample-bootstrap/src/main/resources/sureness.yml, sample-tom/src/main/resources/sureness.yml
support ignore http method request match
docs update: update path match
like:  `  - /api/v3/source===*===[role2]`
=> feature ignore http method

core/src/main/java/com/usthe/sureness/security/XssSqlUtil.java, core/src/test/java/com/usthe/sureness/security/XssSqlUtilTest.java
remove sql inject pattern (--) to ignore match single --, due misjudging jwt
=> remove sql inject pattern (--) 

core/src/main/java/com/usthe/sureness/handler/AttachSessionServletHandler.java, core/src/main/java/com/usthe/sureness/handler/HandlerManager.java, core/src/main/java/com/usthe/sureness/handler/SuccessHandler.java, core/src/main/java/com/usthe/sureness/mgt/SecurityManager.java, core/src/main/java/com/usthe/sureness/mgt/SurenessSecurityManager.java, core/src/main/java/com/usthe/sureness/processor/support/SessionProcessor.java, core/src/main/java/com/usthe/sureness/subject/creater/SessionSubjectServletCreator.java, core/src/main/java/com/usthe/sureness/subject/support/SessionSubject.java
support http session auth
support remeber me
=> support http session

core/src/main/java/com/usthe/sureness/handler/AttachSessionServletHandler.java, core/src/main/java/com/usthe/sureness/handler/HandlerManager.java, core/src/main/java/com/usthe/sureness/handler/SuccessHandler.java, core/src/main/java/com/usthe/sureness/mgt/SecurityManager.java, core/src/main/java/com/usthe/sureness/mgt/SurenessSecurityManager.java, core/src/main/java/com/usthe/sureness/processor/support/SessionProcessor.java, core/src/main/java/com/usthe/sureness/subject/creater/SessionSubjectServletCreator.java, core/src/main/java/com/usthe/sureness/subject/support/SessionSubject.java, samples/pom.xml, samples/sureness-session/pom.xml, samples/sureness-session/sample-session-postman.json, samples/sureness-session/src/main/java/com/usthe/sureness/sample/session/SessionApplication.java, samples/sureness-session/src/main/java/com/usthe/sureness/sample/session/controller/SimulateController.java, samples/sureness-session/src/main/java/com/usthe/sureness/sample/session/sureness/SurenessConfiguration.java, samples/sureness-session/src/main/java/com/usthe/sureness/sample/session/sureness/SurenessFilterExample.java, samples/sureness-session/src/main/resources/application.yml, samples/sureness-session/src/main/resources/sureness.yml
=> add support session sample

samples/pom.xml, samples/sureness-redis-session/pom.xml, samples/sureness-redis-session/sample-session-postman.json, samples/sureness-redis-session/src/main/java/com/usthe/sureness/sample/redis/session/RedisSessionApplication.java, samples/sureness-redis-session/src/main/java/com/usthe/sureness/sample/redis/session/controller/SimulateController.java, samples/sureness-redis-session/src/main/java/com/usthe/sureness/sample/redis/session/sureness/SurenessConfiguration.java, samples/sureness-redis-session/src/main/java/com/usthe/sureness/sample/redis/session/sureness/SurenessFilterExample.java, samples/sureness-redis-session/src/main/resources/application.yml, samples/sureness-redis-session/src/main/resources/sureness.yml
add support redis cache session sample
=> add support redis cache session sample

core/pom.xml, core/src/main/java/com/usthe/sureness/DefaultSurenessConfig.java, core/src/main/java/com/usthe/sureness/subject/creater/BasicSubjectSpringReactiveCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/DigestSubjectSpringReactiveCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/JwtSubjectSpringReactiveCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/JwtSubjectWsJaxRsCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/JwtSubjectWsSpringReactiveCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/NoneSubjectSpringReactiveCreator.java
native support spring webflux in sureness-core
=> support spring5 reactive in sureness-core

README.md, README_CN.md, docs/README.md, docs/_coverpage.md, docs/_navbar.md, docs/cn/README.md, docs/cn/_coverpage.md, docs/cn/_navbar.md
Wow!!  Sureness has transfered to dromara organization.
=> docs update: transfer to dromara organization

samples/pom.xml, samples/zuul-sureness/README.md, samples/zuul-sureness/README_CN.md, samples/zuul-sureness/pom.xml, samples/zuul-sureness/src/main/java/zuul/SurenessZuulApplication.java, samples/zuul-sureness/src/main/java/zuul/sureness/SurenessConfiguration.java, samples/zuul-sureness/src/main/java/zuul/sureness/SurenessFilter.java, samples/zuul-sureness/src/main/resources/application.yml, samples/zuul-sureness/src/main/resources/sureness.yml
Netflix Zuul integrates Sureness to provide API authentication and authorization at the gateway.
=> support example use sureness protect zuul

docs/cn/step-by-step.md
/api/v2/source2===get===[] means that no roles can have access to this resource.
update the step-by-step document.
=> docs update: step-by-step bugfix

sample-bootstrap/src/main/java/com/usthe/sureness/sample/bootstrap/SurenessFilterExample.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/SurenessFilterExample.java, samples/sureness-redis-session/src/main/java/com/usthe/sureness/sample/redis/session/sureness/SurenessFilterExample.java, samples/sureness-session/src/main/java/com/usthe/sureness/sample/session/sureness/SurenessFilterExample.java, samples/zuul-sureness/src/main/java/zuul/sureness/SurenessFilter.java
samples fix information exposure through a stack trace bug
=> samples fix CWE-209

core/src/main/java/com/usthe/sureness/mgt/SurenessSecurityManager.java, core/src/main/java/com/usthe/sureness/processor/exception/UnsupportedSubjectException.java, core/src/main/java/com/usthe/sureness/processor/support/DigestProcessor.java, core/src/main/java/com/usthe/sureness/processor/support/JwtProcessor.java, core/src/main/java/com/usthe/sureness/processor/support/PasswordProcessor.java, core/src/main/java/com/usthe/sureness/subject/Subject.java, core/src/main/java/com/usthe/sureness/subject/support/DigestSubject.java, core/src/main/java/com/usthe/sureness/subject/support/JwtSubject.java, core/src/main/java/com/usthe/sureness/subject/support/NoneSubject.java, core/src/main/java/com/usthe/sureness/subject/support/PasswordSubject.java, core/src/main/java/com/usthe/sureness/subject/support/SessionSubject.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/processor/CustomTokenProcessor.java, sample-tom/src/main/java/com/usthe/sureness/sample/tom/sureness/subject/CustomTokenSubject.java
Optimize some methods to reduce temporary memory usage
1. defalut return exception make singleton instance - `UnsupportedSubjectException`  
2. minimize `subjcet` object creation
=> Optimize some methods to reduce temporary memory usage

core/pom.xml, pom.xml, samples/sureness-spring-boot-starter-example/pom.xml, support/spring-boot-starter-sureness/pom.xml
fix maven publish error, publish sureness-starter to maven central success
=> publish sureness-starter to maven central

.github/workflows/issues-translator.yml
fix bug when issue only has the title
fix bug when only title is not english
=> update issue-translator v2.5 to v2.6

core/src/main/java/com/usthe/sureness/matcher/util/TirePathTree.java, core/src/test/java/com/usthe/sureness/matcher/util/TirePathTreeTest.java
fix https://github.com/dromara/sureness/issues/132 , detail see https://github.com/dromara/sureness/issues/132
=> Misjudging diff permission configurations as same config

core/src/main/java/com/usthe/sureness/handler/AttachSessionServletHandler.java, core/src/main/java/com/usthe/sureness/handler/HandlerManager.java, core/src/main/java/com/usthe/sureness/matcher/DefaultPathRoleMatcher.java, core/src/main/java/com/usthe/sureness/matcher/PathTreeProvider.java, core/src/main/java/com/usthe/sureness/matcher/util/TirePathTree.java, core/src/main/java/com/usthe/sureness/mgt/SurenessSecurityManager.java, core/src/main/java/com/usthe/sureness/processor/exception/NeedDigestInfoException.java, core/src/main/java/com/usthe/sureness/processor/support/DigestProcessor.java, core/src/main/java/com/usthe/sureness/processor/support/JwtProcessor.java
- There was a little code refactor dedicated to avoid :
* null or not null validation, use objets class
* bad imports with overload of resources
* there was code which were not being used so --> remove
* duplication of code is very common
}
=> [Refactor #1] -  Better way to validate, imports and avoid duplicated code.

samples/micro-profile-sureness/README.md, samples/micro-profile-sureness/pom.xml, samples/micro-profile-sureness/src/main/java/com/usthe/sureness/microprofile/DemoRestApplication.java, samples/micro-profile-sureness/src/main/java/com/usthe/sureness/microprofile/HelloController.java, samples/micro-profile-sureness/src/main/java/com/usthe/sureness/microprofile/ResourceController.java, samples/micro-profile-sureness/src/main/java/com/usthe/sureness/microprofile/SurenessFilter.java, samples/micro-profile-sureness/src/main/resources/sureness.yml, samples/micro-profile-sureness/src/main/webapp/WEB-INF/beans.xml, samples/micro-profile-sureness/src/main/webapp/WEB-INF/sureness.yml, samples/micro-profile-sureness/src/main/webapp/index.html, samples/pom.xml
support example use sureness protect microprofile- https://start.microprofile.io/
=> support micro-profile-sureness examples

core/pom.xml, core/src/main/java/com/usthe/sureness/mgt/jwt/DefaultJwtManager.java, core/src/main/java/com/usthe/sureness/mgt/jwt/DefaultRedis.java, core/src/main/java/com/usthe/sureness/mgt/jwt/PassiveExpiringJwtMap.java, core/src/main/java/com/usthe/sureness/provider/ducument/DocumentResourceEntity.java, core/src/main/java/com/usthe/sureness/subject/creater/JwtSubjectJaxRsCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/JwtSubjectServletCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/JwtSubjectSpringReactiveCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/JwtSubjectWsJaxRsCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/JwtSubjectWsServletCreator.java, core/src/main/java/com/usthe/sureness/subject/creater/JwtSubjectWsSpringReactiveCreator.java, core/src/main/java/com/usthe/sureness/util/JsonWebTokenUtil.java, core/src/main/java/com/usthe/sureness/util/SurenessConstant.java, core/src/main/resources/sureness-sample.yml, core/src/test/java/com/usthe/sureness/mgt/jwt/DefaultJwtManagerTest.java, core/src/test/java/com/usthe/sureness/mgt/jwt/DefaultRedisTest.java, core/src/test/java/com/usthe/sureness/mgt/jwt/PassiveExpiringJwtMapTest.java, core/src/test/java/com/usthe/sureness/provider/ducument/DocumentResourceAccessTest.java, core/src/test/java/com/usthe/sureness/subject/creater/JwtSubjectServletCreatorTest.java, core/src/test/java/com/usthe/sureness/util/JsonWebTokenUtilTest.java
Support the management of JWT with default manager. 
Developers can configure the behavior in "tokenCache" attribute in configuration file.
=> feature: support the management of JWT with default manager
